### ISSUE TITLE
Manual approval required for workflow run 7786790649

### ISSUE THREAD

**Issue by pushpendrasingh3** [pushpendrasingh3/argocd-setup#2]
Workflow is pending manual review.
URL: https://github.com/pushpendrasingh3/argocd-setup/actions/runs/7786790649

Required approvers: [pushpendras21 pushpendrasingh3]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by pushpendras21** [comment]
approved

**Comment by pushpendrasingh3** [comment]
approved
